services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: sgcp_backend
    volumes:
      - ./backend/MyDjangoProyect:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - sqlite_data:/app
    env_file: .env
    expose:
      - "8000"
    networks:
      - sgcp_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sgcp_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sgcp_net

volumes:
  static_volume:
  media_volume:
  sqlite_data:

networks:
  sgcp_net:
    driver: bridge