# Usar una versión ligera de Python
FROM python:3.12-slim

# Configurar variables de entorno de Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de dependencias y instalarlas
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el código de tu proyecto al contenedor
COPY . .

# Exponer el puerto 8000 (Vercel usa este puerto por defecto para contenedores)
EXPOSE 8000


# El comando que arranca tu backend. 
# Fíjate que usamos Gunicorn y la ruta a tu wsgi.py
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]