# Generated by Django 6.0.4 on 2026-06-28 02:47

import core.models.usuario
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hair salon',
                'verbose_name_plural': 'Hair salons',
                'db_table': 'hair_salons',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('estilista', 'Estilista'), ('administrador', 'Administrador'), ('recepcionista', 'Recepcionista')], default='cliente', help_text='Rol del usuario en el sistema', max_length=20)),
                ('especialidad', models.CharField(blank=True, help_text='Especialidad del estilista (ej: colorista, barbero)', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('peluqueria', models.ForeignKey(blank=True, help_text='Peluqueria asignada (requerido para rol estilista)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estilistas', to='core.peluqueria')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
            managers=[
                ('objects', core.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dia_semana', models.CharField(help_text='Dia de la semana (ej: lunes, martes)', max_length=20)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del turno')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este horario esta vigente')),
                ('estilista', models.ForeignKey(help_text='Estilista al que pertenece este horario', limit_choices_to={'rol': 'estilista'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'stylist_schedules',
                'ordering': ['estilista__first_name', 'dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('hair_salon', models.ForeignKey(db_column='hair_salon_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.peluqueria')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('modified_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(help_text='Fecha de la cita')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio')),
                ('hora_fin', models.TimeField(help_text='Hora de fin')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la cita', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la cita', null=True)),
                ('cliente', models.ForeignKey(help_text='Cliente que reserva la cita', on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('estilista', models.ForeignKey(help_text='Estilista asignado a la cita', limit_choices_to={'rol': 'estilista'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_estilista', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(help_text='Servicio reservado', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'appointments',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
    ]
